import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; //
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/app/contexts/AuthContext"; // Import

// Sửa lỗi font
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VietNomNom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider> {/* Bọc Provider ở ngoài cùng */}
          <Toaster position="top-center" /> {/* Thêm Toaster */}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}